Se actualizan elementos que renederizan latex en los enunciados
eol-uchile/eol-question-xblock pull request #17
Opened 2024-10-16 20:12 UTC by Lozamded

Se establece en los enunciados que los textos son los que renderizan latex

Se establece dado que esta en producción este xblock como verion 1.0.1

2024-11-05 20:52 UTC, fsologureng requested changes

2024-11-05 20:52 UTC, fsologureng commented on setup.py
> +    version='1.0.1',
me parece que la versión siguiente debería ser `1.0.0`

2024-11-05 21:16 UTC, fsologureng commented on setup.py
> +    version='1.0.1',
Para aclarar, `0.1` es equivalente a `0.1.0`, por tanto un aumento de la mayor version va a `1.0.0`, aunque la naturaleza del cambio creo que debería ser `0.2.0` porque es un cambio menor. Si fuera un fix, sería `0.1.1`.
Sin embargo, como es la primera vez que entran a la notación de 3 dígitos, da lo mismo qué subida de versión eligen. Está súper bien que sea aumento de major version. Por eso me parece más razonable la primera siguiente que es `1.0.0`.
Para más info, ver https://semver.org/lang/es/

2024-11-11 20:20 UTC, vdaiep approved these changes

2024-11-12 12:09 UTC, fsologureng approved these changes

2024-11-12 12:14 UTC, merged